INFO:     Will watch for changes in these directories: ['/Users/sangjaelee/Downloads/blockchain-feature-code_integration']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [82491] using WatchFiles
INFO:     Started server process [82494]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:53790 - "GET /docs HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [82494]
INFO:     Started server process [82571]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'backend.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [82571]
INFO:     Started server process [82590]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'config.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [82590]
INFO:     Started server process [82595]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'mock_run.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [82595]
INFO:     Started server process [82611]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in '.venv/lib/python3.13/site-packages/httpx/_models.py', '.venv/lib/python3.13/site-packages/httpx/_main.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/connection.py', '.venv/lib/python3.13/site-packages/httpcore/_utils.py', '.venv/lib/python3.13/site-packages/httpx/_multipart.py', '.venv/lib/python3.13/site-packages/httpcore/_async/http11.py', '.venv/lib/python3.13/site-packages/httpcore/_async/socks_proxy.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/socks_proxy.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/auto.py', '.venv/lib/python3.13/site-packages/httpcore/_synchronization.py', '.venv/lib/python3.13/site-packages/httpx/_urlparse.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/interfaces.py', '.venv/lib/python3.13/site-packages/httpcore/_async/http_proxy.py', '.venv/lib/python3.13/site-packages/httpx/_api.py', '.venv/lib/python3.13/site-packages/httpx/_content.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/http11.py', '.venv/lib/python3.13/site-packages/httpx/_transports/base.py', '.venv/lib/python3.13/site-packages/httpx/_types.py', '.venv/lib/python3.13/site-packages/httpx/_config.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/__init__.py', '.venv/lib/python3.13/site-packages/httpcore/_exceptions.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/connection_pool.py', '.venv/lib/python3.13/site-packages/httpx/_utils.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/http2.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/sync.py', '.venv/lib/python3.13/site-packages/httpx/__init__.py', '.venv/lib/python3.13/site-packages/httpcore/_async/interfaces.py', '.venv/lib/python3.13/site-packages/httpcore/_trace.py', '.venv/lib/python3.13/site-packages/httpx/_client.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/__init__.py', '.venv/lib/python3.13/site-packages/httpcore/__init__.py', '.venv/lib/python3.13/site-packages/httpx/_decoders.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/base.py', '.venv/lib/python3.13/site-packages/httpcore/_async/__init__.py', '.venv/lib/python3.13/site-packages/httpx/_transports/default.py', '.venv/lib/python3.13/site-packages/httpx/_exceptions.py', '.venv/lib/python3.13/site-packages/httpx/_transports/asgi.py', '.venv/lib/python3.13/site-packages/httpx/_status_codes.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/mock.py', '.venv/lib/python3.13/site-packages/httpcore/_async/connection.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/anyio.py', '.venv/lib/python3.13/site-packages/httpcore/_backends/trio.py', '.venv/lib/python3.13/site-packages/httpcore/_sync/http_proxy.py', '.venv/lib/python3.13/site-packages/httpcore/_async/http2.py', '.venv/lib/python3.13/site-packages/httpcore/_api.py', '.venv/lib/python3.13/site-packages/httpcore/_models.py', '.venv/lib/python3.13/site-packages/httpcore/_ssl.py', '.venv/lib/python3.13/site-packages/httpx/__version__.py', '.venv/lib/python3.13/site-packages/httpx/_transports/wsgi.py', '.venv/lib/python3.13/site-packages/httpx/_transports/mock.py', '.venv/lib/python3.13/site-packages/httpx/_transports/__init__.py', '.venv/lib/python3.13/site-packages/httpcore/_async/connection_pool.py', '.venv/lib/python3.13/site-packages/httpx/_urls.py', '.venv/lib/python3.13/site-packages/httpx/_auth.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [82611]
INFO:     Started server process [82617]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:53853 - "GET /api/v1/donations?limit=50 HTTP/1.1" 200 OK
INFO:     127.0.0.1:53857 - "GET /api/v1/donations?limit=50 HTTP/1.1" 200 OK
INFO:     127.0.0.1:53858 - "GET /api/v1/donations?limit=50 HTTP/1.1" 200 OK
INFO:     127.0.0.1:53859 - "GET /api/v1/donations?limit=50 HTTP/1.1" 200 OK
INFO:     127.0.0.1:53860 - "POST /api/v1/kakaopay/ready HTTP/1.1" 200 OK
INFO:     127.0.0.1:53868 - "POST /api/v1/kakaopay/approve HTTP/1.1" 200 OK
INFO:     127.0.0.1:53897 - "POST /api/v1/kakaopay/approve HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'backend.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [82617]
Process SpawnProcess-7:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/backend.py", line 418
    @app.get("/api/v1/web3/health")
SyntaxError: expected 'except' or 'finally' block
WARNING:  WatchFiles detected changes in 'frontend.py'. Reloading...
Process SpawnProcess-8:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/backend.py", line 418
    @app.get("/api/v1/web3/health")
SyntaxError: expected 'except' or 'finally' block
WARNING:  WatchFiles detected changes in 'backend.py'. Reloading...
Process SpawnProcess-9:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
    ~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 67, in run
    return asyncio.run(self.serve(sockets=sockets))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 71, in serve
    await self._serve(sockets)
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/server.py", line 78, in _serve
    config.load()
    ~~~~~~~~~~~^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/config.py", line 436, in load
    self.loaded_app = import_from_string(self.app)
                      ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/.venv/lib/python3.13/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1160, in get_code
  File "<frozen importlib._bootstrap_external>", line 1090, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Users/sangjaelee/Downloads/blockchain-feature-code_integration/backend.py", line 418
    @app.get("/api/v1/web3/health")
SyntaxError: expected 'except' or 'finally' block
